name: Build Geode Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v3
        with:
          target: Android
          combine: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-bot-android
          path: build/*.geode
          
